#!/bin/sh

set -e

if [ -z $PLUGIN_ROLE ];
then
    echo "Error: please provide aws role to assume"
    exit 1
fi

if [ -z $PLUGIN_FILE ];
then
    PLUGIN_FILE=".env"
fi

echo "Assuming: ${PLUGIN_ROLE}"
CREDS=`aws sts assume-role --role-arn ${PLUGIN_ROLE} --role-session-name=${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}`

AWS_ACCESS_KEY_ID=`echo $CREDS | jq -r '.Credentials.AccessKeyId'`
AWS_SECRET_ACCESS_KEY=`echo $CREDS | jq -r '.Credentials.SecretAccessKey'`
AWS_SESSION_TOKEN=`echo $CREDS | jq -r '.Credentials.SessionToken'`

echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> ${PLUGIN_FILE}
echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> ${PLUGIN_FILE}
echo "export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> ${PLUGIN_FILE}